[package]
name = "talon"
version = "0.1.0"
edition = "2024"

[dependencies]
atty = "0.2.14"
crossterm = "0.29.0"
serenity = { version = "0.12", features = ["framework", "standard_framework"] }
termion = "4.0.5"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
